import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { ethers } from 'ethers';
import { PaymentContract, ContractType } from '../contracts/entities/payment-contract.entity';

// Minimal ABI fragments – full ABIs are generated by Hardhat and imported in production.
const PAYMENT_REGISTRY_ABI = [
  'function anchorProof(bytes32 paymentId) external',
  'function verifyProof(bytes32 paymentId) external view returns (bool)',
];

const ESCROW_FACTORY_ABI = [
  'function createEscrow(address beneficiary, uint256 amount) external returns (address)',
];

const ESCROW_ABI = [
  'function release() external',
  'function refund() external',
  'function dispute() external',
];

const MILESTONE_ABI = [
  'function completeMilestone(uint256 index) external',
  'function cancel() external',
];

@Injectable()
export class BlockchainService implements OnModuleInit {
  private readonly logger = new Logger(BlockchainService.name);
  private provider: ethers.JsonRpcProvider | null = null;
  private signer: ethers.Wallet | null = null;
  private paymentRegistry: ethers.Contract | null = null;
  private escrowFactory: ethers.Contract | null = null;

  constructor(private readonly config: ConfigService) {}

  onModuleInit() {
    const rpcUrl = this.config.get<string>('app.blockchainRpcUrl');
    const privateKey = this.config.get<string>('app.blockchainPrivateKey');

    if (!rpcUrl || !privateKey) {
      this.logger.warn(
        'Blockchain RPC_URL or PRIVATE_KEY not set – blockchain features disabled',
      );
      return;
    }

    try {
      this.provider = new ethers.JsonRpcProvider(rpcUrl);
      this.signer = new ethers.Wallet(privateKey, this.provider);

      const registryAddress = this.config.get<string>('app.paymentRegistryAddress');
      const escrowFactoryAddress = this.config.get<string>('app.escrowFactoryAddress');

      if (registryAddress && registryAddress !== ethers.ZeroAddress) {
        this.paymentRegistry = new ethers.Contract(
          registryAddress,
          PAYMENT_REGISTRY_ABI,
          this.signer,
        );
      }

      if (escrowFactoryAddress && escrowFactoryAddress !== ethers.ZeroAddress) {
        this.escrowFactory = new ethers.Contract(
          escrowFactoryAddress,
          ESCROW_FACTORY_ABI,
          this.signer,
        );
      }

      this.logger.log('BlockchainService initialised');
    } catch (err) {
      this.logger.error('Failed to initialise BlockchainService', err);
    }
  }

  // ── Payment proof anchoring ──────────────────────────────────

  /**
   * Stores a keccak-256 hash of the payment id on-chain.
   * Returns the transaction hash or null when blockchain is not configured.
   */
  async anchorPaymentProof(paymentId: string): Promise<string | null> {
    if (!this.paymentRegistry) return null;

    try {
      const id = ethers.id(paymentId); // keccak256(paymentId)
      const tx = await (this.paymentRegistry.anchorProof as (id: string) => Promise<ethers.ContractTransactionResponse>)(id);
      const receipt = await tx.wait();
      return receipt?.hash ?? null;
    } catch (err) {
      this.logger.error(`anchorPaymentProof failed for ${paymentId}`, err);
      return null;
    }
  }

  /**
   * Returns true when the payment proof exists on-chain.
   */
  async verifyPaymentProof(paymentId: string): Promise<boolean> {
    if (!this.paymentRegistry) return false;

    try {
      const id = ethers.id(paymentId);
      return await (this.paymentRegistry.verifyProof as (id: string) => Promise<boolean>)(id);
    } catch (err) {
      this.logger.error(`verifyPaymentProof failed for ${paymentId}`, err);
      return false;
    }
  }

  // ── Contract deployment ──────────────────────────────────────

  async deployContract(
    contract: PaymentContract,
  ): Promise<{ address: string; txHash: string }> {
    if (!this.escrowFactory || !this.signer) {
      // Return a mock result in development when blockchain is not configured.
      this.logger.warn('EscrowFactory not configured – returning mock deployment result');
      return { address: ethers.ZeroAddress, txHash: '0x' + '0'.repeat(64) };
    }

    if (contract.type === ContractType.ESCROW) {
      const tx = await (this.escrowFactory.createEscrow as (
        beneficiary: string,
        amount: bigint,
      ) => Promise<ethers.ContractTransactionResponse>)(
        contract.beneficiaryRef,
        BigInt(contract.amount),
      );
      const receipt = await tx.wait();
      // The factory emits the new contract address in logs; parse it here.
      const address = receipt?.logs?.[0]?.address ?? ethers.ZeroAddress;
      return { address, txHash: receipt?.hash ?? '0x' };
    }

    throw new Error(`Deployment not yet implemented for contract type: ${contract.type}`);
  }

  // ── Contract actions ─────────────────────────────────────────

  async callContractAction(
    type: ContractType,
    onChainAddress: string,
    action: string,
    params?: Record<string, unknown>,
  ): Promise<string> {
    if (!this.signer) {
      this.logger.warn('Signer not configured – returning mock tx hash');
      return '0x' + '0'.repeat(64);
    }

    const abi = type === ContractType.ESCROW ? ESCROW_ABI : MILESTONE_ABI;
    const instance = new ethers.Contract(onChainAddress, abi, this.signer);

    const tx = await this.dispatchContractAction(type, instance, action, params);
    const receipt = await tx.wait();
    return receipt?.hash ?? '0x';
  }

  /**
   * Dispatches the correct on-chain call based on contract type and action name.
   * Using a switch statement makes it easy to add new contract types in the future.
   */
  private async dispatchContractAction(
    type: ContractType,
    instance: ethers.Contract,
    action: string,
    params?: Record<string, unknown>,
  ): Promise<ethers.ContractTransactionResponse> {
    type ContractFn = () => Promise<ethers.ContractTransactionResponse>;

    switch (type) {
      case ContractType.ESCROW: {
        const escrowActions: Record<string, ContractFn> = {
          release: () => (instance.release as ContractFn)(),
          refund:  () => (instance.refund  as ContractFn)(),
          dispute: () => (instance.dispute as ContractFn)(),
        };
        const fn = escrowActions[action];
        if (!fn) throw new Error(`Unknown escrow action: ${action}`);
        return fn();
      }

      case ContractType.MILESTONE: {
        if (action === 'complete_milestone') {
          const idx = Number(params?.milestoneIndex ?? 0);
          return (instance.completeMilestone as (i: number) => Promise<ethers.ContractTransactionResponse>)(idx);
        }
        if (action === 'cancel') {
          return (instance.cancel as ContractFn)();
        }
        throw new Error(`Unknown milestone action: ${action}`);
      }

      default:
        throw new Error(`Action not supported for contract type: ${type}`);
    }
  }
}
